### ISSUE TITLE
Evolving a pokemon does not mark the evolution as "caught" in the Pokedex

### ISSUE THREAD

**Issue by magroader** [Jerakin/Pokedex5E#465] opened 2020-07-13 16:05 UTC
https://discordapp.com/channels/527605327303147520/562710992753131521/732266142688608407

**Comment by Jerakin** [comment] 2020-07-15 20:50
Can not reproduce this. Will ask the reporter if he got a repro case

**Comment by Jerakin** [comment] 2020-07-15 22:58
User could not reproduce either. Closing as it until we get another user reporting it as without a repro the sample size is too small.

**Closed by Jerakin** 2020-07-15 22:58 UTC
Labels: bug
