### ISSUE TITLE
Feature Request: Calc Skill Mod

### ISSUE THREAD

**Issue by 1dKyro** [Jerakin/Pokedex5E#707] opened 2020-11-24 15:37 UTC
Hey! Was wondering if the feature to have your abiility mod and prof bonus  show up alongside your skills would be possible, for example my spheal is level 2 and has -1 in wisdom, and has proficiency in survival, so they would have a +1. Just think it would be a nice user friendly feature, just unsure of complications or if enough interest has been showed towards this

Thank you for reading! Love the app! <3

**Comment by magroader** [comment] 2020-11-24 15:44
We actually just added this to the list yesterday!

Duplicate of #705 

One subtle issue is that in D&D 5E, skill checks can actually be made with any attribute - for example, you could do Intimidate (Charisma) or, if the DM feels it appropriate, Intimidate (Strength). But that's reasonably rare and I bet people will figure it out.

**Comment by 1dKyro** [comment] 2020-11-24 15:46
Ahh okay awesome didnt realise the dupe! But yeah I think with the any attribute rule thats when it goes more variant and then players can do their own math! But thats more than fair to consider and appreciate the fast response!

**Closed** 2020-11-30 11:18 UTC
